### ISSUE TITLE
API code and DB?

### ISSUE THREAD

**Issue by viktorix** [nekudo/wp_wemahu#1]
Hey, I'm interested in using the plugin for our internal use right now and was curious if it's possible to get the other half of the plugin... code used for the API and ideally DB structure dump. Would really appreciate, although I do understand if not possible. Thanks.

**Comment by nekudo** [comment]
The "Adminpanel" uses a licensed template so I unfortunatly can't just upload the whole code. I'll have to remove some CSS and JS first. Will try do do thant within the next few days.

**Comment by viktorix** [comment]
Is it still available for sale that admin panel? I can pick up a license, make it easier for you.

**Comment by nekudo** [comment]
Okay. I removed the licenced stuff and leaved only the application code. Hopefully it will be useful.

[wmapi.zip](https://github.com/nekudo/wp_wemahu/files/125272/wmapi.zip)
